Application packaged as stand-alone JAR with Spring Boot.
- Added class with 'main' method.
- Packaging method changed from 'war' to 'jar'.
- Added Spring Boot dependencies.

This fails to run with an error caused by:

java.lang.ClassFormatError: Absent Code attribute in method that is not
native or abstract in class file javax/servlet/ServletException